fr_list=[]
fr=input('친구의 이름을 입력하시오: ')
fr_list.append(fr)
fr=input('친구의 이름을 입력하시오: ')
fr_list.append(fr)
fr=input('친구의 이름을 입력하시오: ')
fr_list.append(fr)
fr=input('친구의 이름을 입력하시오: ')
fr_list.append(fr)
fr=input('친구의 이름을 입력하시오: ')
fr_list.append(fr)
